routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/applicant/{id}/send-email', 'ApplicantController@sendEmail');
Route::resource('applicant', 'ApplicantController');

Route::resource('vacancy', 'VacanciesController');

Route::get('/start-test/{key}', 'TestTasks\StartTestTaskController@index');
Route::post('/start-test', 'TestTasks\StartTestTaskController@beginTask');

Route::get('/finish-test/{key}', 'TestTasks\FinishTestTaskController@index');
Route::post('/finish-test', 'TestTasks\FinishTestTaskController@finishTask');

Route::get('/gmail-settings', 'GmailSettingsController@index');
Route::get('/oauth/gmail', 'GmailSettingsController@auth');
Route::get('/oauth/gmail/callback', 'GmailSettingsController@createToken');
Route::get('/oauth/gmail/logout', 'GmailSettingsController@logout');

app/Vacancy.php
<?php

namespace App;

use App\Filters\VacancyFilters;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Nicolaslopezj\Searchable\SearchableTrait;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Vacancy extends Model
{
    use SoftDeletes, SearchableTrait;

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id'];

    /**
     * Searchable rules.
     *
     * @var array
     */
    protected $searchable = [
        /**
         * Columns and their priority in search results.
         * Columns with higher values are more important.
         * Columns with equal values have equal importance.
         *
         * @var array
         */
        'columns' => [
            'vacancies.job_title' => 10,
            'vacancies.email_subject' => 10,
            'vacancies.email_body' => 5,
            'vacancies.time_for_task' => 5,
        ]
    ];

    /**
     * Boot the model.
     */
    public static function boot() {
        parent::boot();

        static::addGlobalScope('applicantCount', function ($builder){
            $builder->withCount('applicants');
        });

        static::deleting(function($vacancy) {
            $vacancy->applicants()->delete();
        });
    }

    /**
     * A vacancy may have many applicants.
     *
     * @return HasMany
     */
    public function applicants()
    {
        return $this->hasMany('App\Applicant');
    }

    /**
     * Apply all relevant vacancy filters.
     *
     * @param  Builder          $query
     * @param  VacancyFilters $filters
     * @return Builder
     */
    public function scopeFilter(Builder $query, VacancyFilters $filters)
    {
        return $filters->apply($query);
    }

    /**
     * Scope a query to only include active vacancies.
     *
     * @param  Builder  $query
     * @return Builder
     */
    public function scopeActive($query)
    {
        return $query->where('active_status', 1);
    }
}

app/Http/Controllers/VacanciesController.php
<?php

namespace App\Http\Controllers;

use App\Filters\VacancyFilters;
use Illuminate\Http\Request;
use App\Vacancy;
use Exception;
use Illuminate\Support\Facades\Session;

class VacanciesController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the vacancy dashboard.
     *
     * @param VacancyFilters $filters
     * @return mixed
     */
    public function index(VacancyFilters $filters)
    {
        $vacancies = Vacancy::latest()->filter($filters)->paginate(10);

        return view('vacancy.index', compact('vacancies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('vacancy.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return mixed
     *
     * @throws Exception
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'job_title'     => 'string|required|max:50',
            'test_task_url' => 'string|max:255|nullable',
            'time_for_task' => 'numeric|max:100|min:1|nullable',
            'email_subject' => 'string|max:255|nullable',
            'email_body'    => 'string|nullable',
            'active_status' => 'boolean|required',
        ]);

        Vacancy::create($request->all());

        Session::flash('flash_message', 'Vacancy added!');

        return redirect('vacancy');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\View\View
     */
    public function show($id)
    {
        $vacancy = Vacancy::findOrFail($id);

        return view('vacancy.show', compact('vacancy'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\View\View
     */
    public function edit($id)
    {
        $vacancy = Vacancy::findOrFail($id);

        return view('vacancy.edit', compact('vacancy'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @param Request $request
     * @return mixed
     *
     * @throws Exception
     */
    public function update($id, Request $request)
    {
        $this->validate($request, [
            'job_title'     => 'string|required|max:50',
            'test_task_url' => 'string|required|max:255|nullable',
            'time_for_task' => 'numeric|max:100|min:1|nullable',
            'email_subject' => 'string|max:255|nullable',
            'email_body'    => 'string|nullable',
            'active_status' => 'boolean|required',
        ]);

        $vacancy = Vacancy::findOrFail($id);
        $vacancy->update($request->all());

        Session::flash('flash_message', 'Vacancy updated!');

        return redirect('vacancy');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return mixed
     */
    public function destroy($id)
    {
        Vacancy::destroy($id);

        Session::flash('flash_message', 'Vacancy deleted!');

        return redirect('vacancy');
    }
}

resources/views/vacancy/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><h3>Create New Vacancy</h3></div>

                <div class="card-body">
                    {!! Form::open([
                        'url' => '/vacancy',
                        'class' => 'form-horizontal',
                        'files' => true
                    ]) !!}

                    @if ($errors->any())
                        <div class="alert alert-danger" role="alert">
                            @foreach ($errors->all() as $error)
                                {{ $error }}<br>
                            @endforeach
                        </div>
                    @endif

                    <div class="form-group row">
                        {!! Form::label('job_title', 'Job Title', ['class' => 'col-md-3 col-form-label']) !!}
                        <div class="col-md-9">
                            {!! Form::text('job_title', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group row">
                        {!! Form::label('test_task_url', 'Test Task URL', ['class' => 'col-md-3 col-form-label']) !!}
                        <div class="col-md-9">
                            {!! Form::text('test_task_url', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group row">
                        {!! Form::label('time_for_task', 'Time For Task (in hours)', ['class' => 'col-md-3 col-form-label']) !!}
                        <div class="col-md-9">
                            {!! Form::number('time_for_task', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group row">
                        {!! Form::label('email_subject', 'Email Title', ['class' => 'col-md-3 col-form-label']) !!}
                        <div class="col-md-9">
                            {!! Form::text('email_subject', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group row">
                        {!! Form::label('email_body', 'Email Body', ['class' => 'col-md-3 col-form-label']) !!}
                        <div class="col-md-9">
                            {!! Form::textarea('email_body', null, ['class' => 'form-control', 'rows' => 4]) !!}
                        </div>
                    </div>
                    <div class="form-group row">
                        {!! Form::label('active_status', 'Active', ['class' => 'col-md-3 col-form-label']) !!}
                        <div class="col-md-9">
                            {!! Form::checkbox('active_status', true, true, ['class' => 'form-control']) !!}
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="offset-md-3 col-md-9">
                            {!! Form::submit('Create', ['class' => 'btn btn-primary']) !!}
                        </div>
                    </div>
                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/vacancy/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><h3>Edit Vacancy - {{ $vacancy->job_title }}</h3></div>

                <div class="card-body">
                    {!! Form::model($vacancy, [
                        'method' => 'PATCH',
                        'url' => ['/vacancy', $vacancy->id],
                        'class' => 'form-horizontal',
                        'files' => true
                    ]) !!}

                    @if ($errors->any())
                        <div class="alert alert-danger" role="alert">
                            @foreach ($errors->all() as $error)
                                {{ $error }}<br>
                            @endforeach
                        </div>
                    @endif

                    <div class="form-group row">
                        {!! Form::label('job_title', 'Job Title', ['class' => 'col-md-3 col-form-label']) !!}
                        <div class="col-md-9">
                            {!! Form::text('job_title', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group row">
                        {!! Form::label('test_task_url', 'Test Task URL', ['class' => 'col-md-3 col-form-label']) !!}
                        <div class="col-md-9">
                            {!! Form::text('test_task_url', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group row">
                        {!! Form::label('time_for_task', 'Time For Task (in hours)', ['class' => 'col-md-3 col-form-label']) !!}
                        <div class="col-md-9">
                            {!! Form::number('time_for_task', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group row">
                        {!! Form::label('email_subject', 'Email Title', ['class' => 'col-md-3 col-form-label']) !!}
                        <div class="col-md-9">
                            {!! Form::text('email_subject', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group row">
                        {!! Form::label('email_body', 'Email Body', ['class' => 'col-md-3 col-form-label']) !!}
                        <div class="col-md-9">
                            {!! Form::textarea('email_body', null, ['class' => 'form-control', 'rows' => 4]) !!}
                        </div>
                    </div>
                    <div class="form-group row">
                        {!! Form::label('active_status', 'Active', ['class' => 'col-md-3 col-form-label']) !!}
                        <div class="col-md-9">
                            {!! Form::checkbox('active_status', true, $vacancy->active_status, ['class' => 'form-control']) !!}
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="offset-md-3 col-md-9">
                            {!! Form::submit('Update', ['class' => 'btn btn-primary']) !!}
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/vacancy/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div class="level">
            <span class="flex">
                <h1 class="mb-3">Vacancies <a href="{{ url('/vacancy/create') }}" class="btn btn-primary btn-sm" title="Add New Vacancy"><i class="fas fa-plus"></i></a></h1>
            </span>
            <form class="form-search" action="{{ url('/vacancy') }}" method="get" role="search">
                <div class="input-group">
                    <input type="text" class="form-control" name="search" placeholder="Search...">
                </div>
            </form>
        </div>

        <div class="table">
            <table class="table table-bordered table-striped table-hover">
                <thead>
                <tr>
                    <th> Job Title </th>
                    <th style="max-width: 60px;"> Applicants </th>
                    <th style="max-width: 70px;"> Time For Task </th>
                    <th class="text-center"> Status </th>
                    <th style="min-width: 126px">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($vacancies as $vacancy)
                    <tr>
                        <td>{{ $vacancy->job_title }}</td>
                        <td class="text-center">{{ $vacancy->applicants_count }}</td>
                        <td class="text-center">{{ $vacancy->time_for_task }}</td>
                        <td class="text-center">
                            @if ($vacancy->active_status === 1)
                                <span class="badge badge-success">active</span>
                            @else
                                <span class="badge badge-secondary">inactive</span>
                            @endif
                        </td>
                        <td>
                            <a href="{{ url('/vacancy/' . $vacancy->id) }}" class="btn btn-success btn-sm" title="View Vacancy"><i class="far fa-eye"></i></a>
                            <a href="{{ url('/vacancy/' . $vacancy->id . '/edit') }}" class="btn btn-primary btn-sm" title="Edit Vacancy"><i class="fas fa-pencil-alt"></i></a>
                            {!! Form::open([
                                'method'=>'DELETE',
                                'url' => ['/vacancy', $vacancy->id],
                                'style' => 'display:inline'
                            ]) !!}
                            {!! Form::button('<i class="far fa-trash-alt"></i>', array(
                                    'type' => 'submit',
                                    'class' => 'btn btn-danger btn-sm',
                                    'title' => 'Delete Vacancy',
                                    'onclick'=>'return confirm("Confirm delete?")'
                            )) !!}
                            {!! Form::close() !!}
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            <div class="pagination-wrapper"> {!! $vacancies->render() !!} </div>
        </div>

    </div>
@endsection

resources/views/vacancy/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <h1>{{ $vacancy->job_title }}
        <a href="{{ url('vacancy/' . $vacancy->id . '/edit') }}" class="btn btn-primary btn-sm" title="Edit Vacancy"><i class="fas fa-pencil-alt"></i></a>
        {!! Form::open([
            'method'=>'DELETE',
            'url' => ['vacancy', $vacancy->id],
            'style' => 'display:inline'
        ]) !!}
        {!! Form::button('<i class="far fa-trash-alt"></i>', array(
            'type' => 'submit',
            'class' => 'btn btn-danger btn-sm',
            'title' => 'Delete Vacancy',
            'onclick'=>'return confirm("Confirm delete?")'
        ))!!}
        {!! Form::close() !!}
    </h1>
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-hover">
            <tbody>
                <tr>
                    <th>ID</th><td>{{ $vacancy->id }}</td>
                </tr>
                <tr>
                    <th> Job Title </th><td> {{ $vacancy->job_title }} </td>
                </tr>
                <tr>
                    <th> Test Task URL </th><td> {{ $vacancy->test_task_url }} </td>
                </tr>
                <tr>
                    <th> Time For Task </th><td> {{ $vacancy->time_for_task }} </td>
                </tr>
                <tr>
                    <th> Email Subject </th><td> {{ $vacancy->email_subject }} </td>
                </tr>
                <tr>
                    <th> Email Body </th><td> {{ $vacancy->email_body }} </td>
                </tr>
                <tr>
                    <th> Active Status </th>
                    <td>
                        @if ($vacancy->active_status === 1)
                            <span class="badge badge-success">active</span>
                        @else
                            <span class="badge badge-secondary">inactive</span>
                        @endif
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

</div>
@endsection